### ISSUE TITLE
Make more clear report is not real

### ISSUE THREAD

**Issue by cranmer** [Monica0905/Needs-Assessment-Decoy-Sample#1]
Hi @Monica0905 
Could you modify the Rmd for the report and the generated PDF so that it is more clear that this is not the result of a real survey? It is clear in the repository, but the PDF on its own could give the wrong impression.
Thanks!

**Comment by Monica0905** [comment]
Sure! Changes done!

**Comment by cranmer** [comment]
Thanks!
