### ISSUE TITLE
Change name of repo?

### ISSUE THREAD

**Issue by cranmer** [Monica0905/Needs-Assessment-Decoy-Sample#3]
Hi @Monica0905 

I'm wondering what you think about changing the name of the repository. To me, the word "decoy" implies some kind of deception, like we are trying to trick someone with a look-alike. Would you mind if we changed it to: "Needs-Assessment-Survey-Template" ?

You can access that in the Settings tab.

**Comment by Monica0905** [comment]
Sure! That sounds good! I have changed the name :)

**Comment by cranmer** [comment]
Thanks!

**Comment by Monica0905** [comment]
No prob!
