### ISSUE TITLE
Transfer repo to DS3?

### ISSUE THREAD

**Issue by cranmer** [Monica0905/Needs-Assessment-Decoy-Sample#4]
Hi @Monica0905 and @sinclert

Would it be ok if we transferred this repository to the ds3-nyu organization?
https://github.com/ds3-nyu

If we do, it makes sense for you to put your name on the README more visibly. Also, you can fork the repository after if you would like a copy of it to be displayed in your personal area.

Here are some instructions:
https://help.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

@Sinclert,  I think that @Monica0905 will need to be a member of the DS3 organization and have permission to create a repository there. Slightly different information at this link:
https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by Sinclert** [comment]
We discussed it brieftly over email.

I will send @Monica0905 an organization invitation email. Please, let me know if there is any problem during the process.

**Comment by Monica0905** [comment]
Received! Thanks Sinclert!

**Comment by Monica0905** [comment]
The transferring is done!

**Comment by cranmer** [comment]
Thanks! you rock!

**Comment by Monica0905** [comment]
No prob!! ;)
